Pooja/Pooja/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import about
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles.views import articles_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_list, name="home"),
    path('about/', about, name="about"),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pooja/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

Pooja/articles/urls.py
from django.urls import path
from .views import articles_list, article_create, article_detail

app_name = 'articles'

urlpatterns = [
    path('', articles_list, name='list'),
    path('create/', article_create, name="create"),
    path('<slug:slug>/', article_detail, name="detail")
]

Pooja/accounts/models.py
from django.db import models

# Create your models here.

Pooja/articles/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    dateTime = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Pooja/articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body', 'thumb']

Pooja/Pooja/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

Pooja/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

Pooja/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def articles_list(request):
    articles = Article.objects.all().order_by('dateTime')
    return render(request, 'articles/articles_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

Pooja/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Log In">
</form>
{% endblock %}

Pooja/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Signup</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Sign Up">
</form>
{% endblock %}

Pooja/articles/templates/articles/article_create.html
{% extends 'base.html' %}
{% block content %}
<div class="article-create">
    <h1>Create Article</h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
    </form>
</div>
{% endblock %}

Pooja/articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="article_detail">
    <div class="article">
        <h1>{{ article.title }}</h1>
        <img src="{{ article.thumb.url }}"/>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

Pooja/articles/templates/articles/articles_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="js-fullheight d-flex justify-content-center align-items-center">
            <div class="col-md-8 text text-center">
                <div class="img mb-4" style="background-image: url({% static 'images/author.jpg' %});"></div>
                <div class="desc">
                    <h2 class="subheading">Hello I'm</h2>
                    <h1 class="mb-4">Pooja Thapa</h1>
                    <p class="mb-4">A Hotel Management graduate, a travel enthusiast and a movie critic.<br/>
Welcome to the journey through old and critically acclaimed cinema works, into the landscape visits in Nepal, China and India and across college experiences gathered during the bachelors in the city of temples, Kathmandu.</p>
                    <p><a href="{% url 'about' %}" class="btn-custom">More About Me <span class="ion-ios-arrow-forward"></span></a></p>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section" id="articles_div">
        <div class="container">
            <div class="row justify-content-center mb-5 pb-2">
                <div class="col-md-7 heading-section text-center ftco-animate">
                    <h2 class="mb-4">Articles</h2>
                    <p>With a sole purpose for eliminating values received by undeserved works, these articles target reality we haven't discussed openly about.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {% for article in articles %}
                    <div class="col-md-4">
                        <div class="blog-entry ftco-animate">
                            <a href="#"><img src="{{ article.thumb.url }}" class="img img-2"></a>
                            <div class="text text-2 pt-2 mt-3">
                                <h3 class="mb-4"><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h3>
                                <p class="mb-4">{{article.body|truncatechars:100}}...</p>
                                <div class="author mb-4 d-flex align-items-center">
                                    <div class="ml-3 info">
                                        <h3><span>{{article.dateTime}}</span></h3>
                                    </div>
                                </div>
                                <div class="meta-wrap align-items-center">
                                    <div class="half">
                                        <p><a href="{% url 'articles:detail' slug=article.slug %}" class="btn py-2">Continue Reading <span class="ion-ios-arrow-forward"></span></a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Pooja/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="js-fullheight d-flex justify-content-center align-items-center">
            <div class="col-md-8 text text-center">
                <div class="desc">
                    <h1 class="mb-4">About Me</h1>
                    <p class="mb-4">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>
                    <ul class="ftco-social mt-3">
                        <li class="ftco-animate"><a href="https://www.facebook.com/pooja.thapa.393"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/poojeh/"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
</div>
{% endblock %}

Pooja/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Pooja Thapa</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
			<h1 id="colorlib-logo"><a href="{% url 'home' %}">Poojeh<span>.</span></a></h1>
			<nav id="colorlib-main-menu" role="navigation">
				<ul>
					<li class="colorlib-active"><a href="{% url 'home' %}">Home</a></li>
					<li><a href="{% url 'articles:list' %}#articles_div">Articles</a></li>
					<li><a href="{% url 'about' %}">About</a></li>
					<li><a href="#contact_div">Contact</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Log Out</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                    {% endif %}
				</ul>
                <div style="font-size: 14px; font-weight: 400; color: rgba(0, 0, 0, 0.6);">
                    <ul>
                        <li style="display: inline; padding-right:2.5px; padding-left:2.5px"><a href="https://www.facebook.com/pooja.thapa.393"><i class="icon-facebook"></i></a></li>
					    <li style="display: inline; padding-right:2.5px; padding-left:2.5px"><a href="https://www.instagram.com/poojeh/"><i class="icon-instagram"></i></a></li>
                    </ul>
                </div>
			</nav>
		</aside> <!-- END COLORLIB-ASIDE -->
        <div id="colorlib-main">
        {% block content %}
        {% endblock %}
            <footer class="ftco-footer ftco-bg-dark ftco-section" id="contact_div">
                <div class="container px-md-5">
                    <div class="row mb-5">
                        <div class="col-md">
                            <div class="ftco-footer-widget mb-4">
                                <h2 class="ftco-heading-2">Have any Questions or Suggestions?</h2>
                                <div class="block-23 mb-3">
                                    <ul>
                                        <li><span class="icon icon-map-marker"></span><span class="text" style="font-weight: normal; color:white">Ganeshpur-4, Nepalgunj</span></li>
                                        <li><span class="icon icon-phone"></span><span class="text" style="font-weight: normal; color:white">+977 9840715749</span></li>
                                        <li><span class="icon icon-envelope"></span><span class="text" style="font-weight: normal; color:white">pooja1996@gmail.com</span></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <p style="text-align:center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            </footer>
        </div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->
  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>